name: CD

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    if: github.event.pull_request.merged == true
    steps:
      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ec2-user/FE_Huggie/
            mkdir move-dir
            git checkout develop
            git pull
            docker-compose build
            mkdir test-before
            docker-compose up -d
            mkdir test-after
