# name: CI/CD
# on:
#   push:
#     branches:
#       - develop
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.1
#         with:
#           persist-credentials: false

#       - name: Install and Test
#         # uses: actions/setup-node@v1
#       - run: yarn install
#       - run: yarn test
#       - run: npm run build
#       - run: npm run export
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@3.7.1
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: develop  # 배포될 브랜치
#           FOLDER: out # 이 폴더에 있는 파일을 배포
# # 배포 브랜치에 있는 파일들을 자동으로 삭제
# #           CLEAN: true 
name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  # test:
  #   name: Jest Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Install Dependencies
  #     run: yarn install

  #   - name: Run Jest Tests
  #     run: yarn test
  
  deploy:
    name: Deploy to release
    runs-on: ubuntu-latest
    # needs: test
    if: ${{ success() }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: release
    - name: Configure Git
      env:
        GIT_USER_NAME: ${{ github.actor }}
        GIT_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
    - name: Merge changes
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        git merge ${{ github.sha }}
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
