name: CI/CD Workflow
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy to release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: release
    - name: Configure Git and Merge changes
      env:
        GIT_USER_NAME: ${{ github.actor }}
        GIT_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        git merge release
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: release
        github_token: ${{ secrets.GITHUB_TOKEN }}
