name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  merge-and-deploy:
    name: Merge and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Configure Git
      env:
        GIT_USER_NAME: ${{ github.actor }}
        GIT_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"

    - name: Check for conflicts
      run: |
        git fetch origin
        git diff --name-only HEAD origin/develop --exit-code || (echo "Merge conflict detected"; exit 1)

    - name: Merge changes
      run: |
        git merge origin/develop
        echo "Merge successful!"

