name: CICD

on:
  pull_request:
    branches:
      - develop
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Request random review
        uses: maxkomarychev/octions/request-random-reviewer@v1
        with:
          repository: ${{ github.repository }}
          pull_request_number: ${{ github.event.pull_request.number }}
          team_reviewers_only: true
          token: ${{ secrets.GITHUB_TOKEN }}