name: CI/CD Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      # - name: Run tests
      #   run: npm test

  assign-reviewer:
    name: Assign Reviewer
    runs-on: ubuntu-latest
    # needs: test
    # if: ${{ always() }}
    steps:
      - name: Assign Random Reviewer
        uses: chrnorm/assign-random-reviewer-action@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          team-reviewers: |
            team-1
            team-2
          max-retries: 10
          retry-backoff-seconds: 3

  merge:
    name: Merge to Develop
    runs-on: ubuntu-latest
    needs: assign-reviewer
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Merge pull request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: 'Merge pull request #${{ github.event.pull_request.number }} from ${GITHUB_REPOSITORY}}/${{ github.event.pull_request.head.ref }}'
          title: 'Merge pull request #${{ github.event.pull_request.number }} from ${GITHUB_REPOSITORY}}/${{ github.event.pull_request.head.ref }}'
          branch: develop
          delete-branch: true
          labels: auto-merge
          token: ${{ secrets.GITHUB_TOKEN }}
