# name: CI/CD Workflow

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   test:
#     name: Jest Tests
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Install Dependencies
#       run: yarn install

#     - name: Run Jest Tests
#       run: yarn test
  
#   deploy:
#     name: Deploy to develop
#     runs-on: ubuntu-latest
#     needs: test
#     if: ${{ success() }}
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         ref: develop

#     - name: Merge changes
#       run: |
#         git config --global user.name "Your Name"
#         git config --global user.email "your-email@example.com"
#         git merge ${{ github.sha }}
        
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         branch: develop
#         github_token: ${{ secrets.G_TOKEN }}





#   deploy:
#     name: Deploy to AWS
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up SSH connection
#       uses: webfactory/ssh-agent@v0.5.0
#       with:
#         ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

#     - name: Install Docker
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y docker.io
#         sudo systemctl start docker
#         sudo systemctl enable docker

#     - name: Pull Latest Code
#       run: |
#         cd /path/to/project
#         git pull

#     - name: Build and Run Docker Compose
#       run: |
#         cd /path/to/project
#         docker-compose build
#         docker-compose up -d
